/*
 * DIO_Config.h
 *
 *  Created on: Feb 10, 2023
 *      Author: dell
 */

#ifndef DIO_CONFIG_H
#define DIO_CONFIG_H

/*PORTA PINS Directions*/
#define DIO_PORTA_PIN0_INIT_DIR		INPUT
#define DIO_PORTA_PIN1_INIT_DIR		INPUT
#define DIO_PORTA_PIN2_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN3_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN4_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN5_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN6_INIT_DIR		OUTPUT
#define DIO_PORTA_PIN7_INIT_DIR		OUTPUT

/*PORTB PINS Directions*/
#define DIO_PORTB_PIN0_INIT_DIR		INPUT
#define DIO_PORTB_PIN1_INIT_DIR		INPUT
#define DIO_PORTB_PIN2_INIT_DIR		INPUT
#define DIO_PORTB_PIN3_INIT_DIR		INPUT
#define DIO_PORTB_PIN4_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN5_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN6_INIT_DIR		OUTPUT
#define DIO_PORTB_PIN7_INIT_DIR		OUTPUT

/*PORTC PINS Directions*/
#define DIO_PORTC_PIN0_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN1_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN2_INIT_DIR		OUTPUT
#define DIO_PORTC_PIN3_INIT_DIR		INPUT
#define DIO_PORTC_PIN4_INIT_DIR		INPUT
#define DIO_PORTC_PIN5_INIT_DIR		INPUT
#define DIO_PORTC_PIN6_INIT_DIR		INPUT
#define DIO_PORTC_PIN7_INIT_DIR		INPUT

/*PORTD PINS Directions*/
#define DIO_PORTD_PIN0_INIT_DIR  OUTPUT   //Rx
#define DIO_PORTD_PIN1_INIT_DIR  OUTPUT	 //Tx
#define DIO_PORTD_PIN2_INIT_DIR  INPUT
#define DIO_PORTD_PIN3_INIT_DIR  INPUT
#define DIO_PORTD_PIN4_INIT_DIR  OUTPUT
#define DIO_PORTD_PIN5_INIT_DIR  OUTPUT
#define DIO_PORTD_PIN6_INIT_DIR  OUTPUT
#define DIO_PORTD_PIN7_INIT_DIR  OUTPUT

/*PORTA PIN Values*/

#define DIO_PORTA_PIN0_INIT_VAL  LOW
#define DIO_PORTA_PIN1_INIT_VAL  LOW
#define DIO_PORTA_PIN2_INIT_VAL  HIGH
#define DIO_PORTA_PIN3_INIT_VAL  LOW
#define DIO_PORTA_PIN4_INIT_VAL  LOW
#define DIO_PORTA_PIN5_INIT_VAL  LOW
#define DIO_PORTA_PIN6_INIT_VAL  LOW
#define DIO_PORTA_PIN7_INIT_VAL  LOW

/*PORTB PINS Values*/
#define DIO_PORTB_PIN0_INIT_VAL  HIGH
#define DIO_PORTB_PIN1_INIT_VAL  HIGH
#define DIO_PORTB_PIN2_INIT_VAL  HIGH
#define DIO_PORTB_PIN3_INIT_VAL  HIGH
#define DIO_PORTB_PIN4_INIT_VAL  HIGH
#define DIO_PORTB_PIN5_INIT_VAL  HIGH
#define DIO_PORTB_PIN6_INIT_VAL  HIGH
#define DIO_PORTB_PIN7_INIT_VAL  HIGH

/*PORTC PINS Values*/
#define DIO_PORTC_PIN0_INIT_VAL  HIGH
#define DIO_PORTC_PIN1_INIT_VAL  HIGH
#define DIO_PORTC_PIN2_INIT_VAL  LOW
#define DIO_PORTC_PIN3_INIT_VAL  LOW
#define DIO_PORTC_PIN4_INIT_VAL  LOW
#define DIO_PORTC_PIN5_INIT_VAL  LOW
#define DIO_PORTC_PIN6_INIT_VAL  LOW
#define DIO_PORTC_PIN7_INIT_VAL  LOW

/*PORTD PINS Values*/
#define DIO_PORTD_PIN0_INIT_VAL  HIGH
#define DIO_PORTD_PIN1_INIT_VAL  HIGH
#define DIO_PORTD_PIN2_INIT_VAL  HIGH
#define DIO_PORTD_PIN3_INIT_VAL  HIGH
#define DIO_PORTD_PIN4_INIT_VAL  LOW
#define DIO_PORTD_PIN5_INIT_VAL  LOW
#define DIO_PORTD_PIN6_INIT_VAL  LOW
#define DIO_PORTD_PIN7_INIT_VAL  HIGH


#endif /* MCAL_DIO_DIO_CONFIG_H_ */
